db.host=localhost
db.port=3306
db.name=fishdadb
db.user=root
db.password=root
game.default-username=admin
game.default-password=12345678
db.shell=bash -c
db.mysql-path=mariadb
db.mysql-dump-path=mariadb-dump
db.backup-path=backup/backup.sql

# https://pixabay.com/sound-effects/nature-splashing-water-443136/
game.attack-sfx-path=assets/attack.wav
